/**:
  ros__parameters:
    model: Pinhole
    width: 2448
    height: 2048
    scale: 0.25
    fx: 1444.431662789634
    fy: 1444.343536688358
    cx: 1177.801079401826
    cy: 1043.601026568268
    d0: -0.05729528706141188
    d1: 0.1210407244166642
    d2: 0.001274128378760289
    d3: 0.0004389741530109464

    # AMtown AMvalley
    # cam_width: 2448
    # cam_height: 2048
    # scale: 0.25
    # cam_fx: 1453.88
    # cam_fy: 1452.85
    # cam_cx: 1182.53
    # cam_cy: 1045.82 
    # cam_d0: -0.052
    # cam_d1: 0.1168
    # cam_d2: 0.0015
    # cam_d3: 0.00013