/**:
  ros__parameters:
    cam_model: Pinhole
    cam_width: 1280
    cam_height: 720
    scale: 1.0
    cam_fx: 643.6208652685277
    cam_fy: 606.338210828594
    cam_cx: 639.379735810656
    cam_cy: 365.5472566365266
    cam_d0: -0.05596842989325523
    cam_d1: 0.06889437139034271
    cam_d2: -0.0001148505107266828
    cam_d3: 0.0007815142744220793
